apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-app
  labels:
    app: express
spec:
  selector:
    matchLabels:
      app: express
  replicas: 1
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
      - name: express-cont
        #image: ghcr.io/adamroddick/node-express-mysql:master
        image: nginx:alpine
        ports:
          - containerPort: 80
            protocol: TCP
        resources:
          requests:
            memory: 64Mi
            cpu: 100m
          limits:
            memory: 128Mi
            cpu: 200m
