apiVersion: v1
kind: Service
metadata:
  name: express-svc
  namespace: express-ns
  labels:
    app: express-app
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: express